version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: hypesoft-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hypesoft
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - hypesoft-network

  # MongoDB Express 
  mongo-express:
    image: mongo-express:1.0
    container_name: hypesoft-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: express
    depends_on:
      - mongodb
    networks:
      - hypesoft-network

  # Keycloak 
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: hypesoft-keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --import-realm
    depends_on:
      - mongodb
    networks:
      - hypesoft-network

  # Backend .NET
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypesoft-backend
    restart: unless-stopped
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://admin:password@mongodb:27017/
      - Keycloak__Authority=http://keycloak:8080/realms/hypesoft-realm
      - Keycloak__Audience=hypesoft-api
    volumes:
      - ./backend:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      - mongodb
      - keycloak
    networks:
      - hypesoft-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypesoft-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=hypesoft-realm
      - VITE_KEYCLOAK_CLIENT_ID=hypesoft-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hypesoft-network

  nginx:
    image: nginx:alpine
    container_name: hypesoft-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hypesoft-network

volumes:
  mongodb_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  hypesoft-network:
    driver: bridge